// Users
export const GET_USERS = "GET_USERS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//Questions
export const POST_QUESTIONS = "POST_QUESTIONS";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_ANSWERED_AND_UNANSWERED_QUESTIONS = "GET_ANSWERED_AND_UNANSWERED_QUESTIONS";
export const GET_SELECTED_QUESTION = "GET_SELECTED_QUESTION";
export const SAVE_ANSWER = "SAVE_ANSWER";

